
{% set data = load_setup_py_data() %}
{% set rosetta = data["conda_rosetta_stone"] %}

package:
  name: darknet.py

  version: {{ data['version'] }}

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  {%- if 'entry_points' in data and 'console_scripts' in data['entry_points'] %}
  entry_points:
    {% for entry in data['entry_points']['console_scripts'] %}
      {%- set kv = entry.split('=') %}
      - {{ kv[0].strip() }} = {{ kv[1].strip() }}
    {% endfor %}
  {%- endif %}

requirements:
  # if you need compilers, uncomment these
  #    read more at https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
  build:
    - {{ compiler('c') }}

  host:
    - python {{ python }}
    - pip
    {% for dep in data['setup_requires'] %}
    - {{ rosetta.get(dep, dep).lower() }}
    {% endfor %}
    {% for dep in data['conda_requires']['host'] %}
    - {{ rosetta.get(dep, dep).lower() }}
    {% endfor %}
  run:
    - python
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ rosetta.get(dep, dep).lower() }}
    {% endfor %}
    {% for dep in data['conda_requires']['run'] %}
    - {{ rosetta.get(dep, dep).lower() }}
    {% endfor %}
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - tests
  requires:
    # dependencies are defined in setup.py
    {% for dep in data['tests_require'] %}
    - {{ rosetta.get(dep, dep).lower() }}
    {% endfor %}

  commands:
    {%- if 'entry_points' in data and 'console_scripts' in data['entry_points'] %}
    {%- for entry in data['entry_points']['console_scripts'] %}
    - {{ entry.split('=')[0].strip() }} --help
    {%- endfor %}
    {%- endif %}
    - pytest tests

about:
  home: https://github.com/zeroae/darknet.py
  summary: DarkNet OpenSource Neural Networks in Python
  license: {{ data.get('license') }}
  license_file: LICENSE
